spring:
  rabbitmq:
    username: user
    password: user
  application:
    name: order
server:
  port: 9091
# eureka:
#   client:
#    register-with-eureka: false  # 当前微服务不注册到eureka中(只作为消费端，不作为服务提供端，并不对外提供服务)
#     service-url:
#       defaultZpne: http://localhost:8762/eureka/

  instance:
      hostname: localhost
      
environment: dev
