server:
  port: 9090
spring:
  application:
    name: product
  rabbitmq:
    username: user
    password: user
eureka:
  client:
    service-url:
      defaultZpne: http://localhost:8762/eureka/

  instance:
    hostname: localhost
